<?php

namespace backend\controllers;
use backend\models\service\YhtService;
use Yii;
use common\helpers\FuncHelper as output;

class YhtController extends \yii\web\Controller
{
    public $layout = 'yhtmain';
    /**
     * @var YhtService
     */
    private $service;
    public function init()
    {
        $this->service = new YhtService;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        if (!Yii::$app->request->isAjax && $action->id!='index'){
            die("请求出错");
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionStats(){
        $res = $this->service->Stats();
        output::ajaxReturn(200,'success',$res);
    }
}
