<?php

namespace frontend\controllers;
use Yii;
use yii\web\Controller;

class IndexController extends Controller
{
    /**
     * @var string
     */
//    public $layout = 'main';
    public $layout = 'kjmain';

//    public function actionIndexdef()
//    {
//        return $this->render('index');
//    }

    /**
     * @var
*/
    public function init()
    {
        //平台验证和授权验证
        if (Yii::$app->wechat->isWechat && !Yii::$app->wechat->isAuthorized()){
            Yii::$app->wechat->authorizeRequired()->send();
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
//        wxlog(json_encode($_GET));
        //验证服务器
        if (Yii::$app->request->get('echostr',false)){
            //执行服务端业务
            $response = Yii::$app->wechat->server->serve();
            // 将响应输出
            $response->send();
        }
        //业务页面，也就是需要授权才能访问的页面
        //砍价活动页
        return $this->render('kanjia');
    }

    /**
     * @return 砍价详情
     */
    public function actionDetail(){
        return $this->render('kj-detail');
    }

    /**
     * @return 砍价详情
     */
    public function actionUser(){
        return $this->render('kj-detail');
    }

    public function actionClear(){
        Yii::$app->session->removeAll();
        p(Yii::$app->session);
    }
}
