<?php

namespace console\controllers;
use common\widgets\Uploader;
use Yii;
use yii\db\Query;

/**
 * Class FakeController
 * @package console\controllers
 * @property Uploader|\common\widgets\Uploader $uploadAli
 */
class FakeController extends \yii\console\Controller
{
    private $uploadAli;
    function init()
    {
        Yii::$app->setComponents(
            [
                'db' => [
                    'class'       => 'yii\db\Connection',
                    'dsn'         => 'mysql:host=gz-cdb-ecmy83dx.sql.tencentcdb.com;port=62387;dbname=bdm314524321_db',
                    'username'    => 'root',
                    'password'    => 'hjzhome888',
                    'charset'     => 'utf8',
                    'tablePrefix' => 'ecs_',
                ],
            ]
        );
        $this->uploadAli = new Uploader();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function upload($path)
    {
        //获取荟家装服务器图片, 判断本地是否存在, 不存在则获取图片保存在临时文件夹, 再用临时地址上传到顽兔, 上传前验证文件目录是否存在
        try{
            $root = "http://www.hjzhome.com/";
            $localRoot = "E:\phpStudy\PHPTutorial\WWW\hjz\htdocs/";
            $localPutRoot = "E:\phpStudy\PHPTutorial\WWW\hjz\htdocs/images/alishi/";

            $filename = $root.$path;//远程地址
            $localFilename = $localRoot.$path;//本地图片库
            $localPutFilename = $localPutRoot.basename($path);//本地临时图片地址
            $utf8PutFilename = iconv("utf-8","gbk", $localPutFilename);//utf8 本地临时图片地址
            $space = 'hjzimage'; //顽兔图片空间
            $spacePath = dirname($path); //空间相对路径

            if (!is_file($localFilename)){
                //保存到临时文件夹
                $img = file_get_contents($filename);
                // 中文地址需要转码为 utf8 才能保存在本地
                file_put_contents($utf8PutFilename, $img);
                $localFilename = $localPutFilename;
            }
            $wtRes = $this->uploadAli->test_upload_file_c($localFilename, $space, $spacePath);
            return $wtRes;
        }catch (\Exception $e){
            p($e->getMessage());
            return [];
        }
    }

    /**
     * 缩略图,封面上传到百川顽兔
     * @param int $start
     * @param int $end
     * @throws \yii\db\Exception
     */
    public function actionGetData($start=0, $end=0){
        $db = Yii::$app->getDb();
        $data = (new Query())->select("goods_id,tuijie_img,goods_thumb,goods_img,original_img")
            ->from("ecs_goods")
            ->where(['between', 'goods_id', $start, $end])
            ->all($db);
        foreach ($data as $goodimgs){
            $status = ['good_id'=>$goodimgs['goods_id'], 'tuijie_img'=>0,'goods_thumb'=>0,'goods_img'=>0,'original_img'=>0];
            foreach ($goodimgs as $attr => $img){
                if ($attr!="goods_id" && $img){
                    $res = $this->upload($img);
                    if (array_key_exists('code',$res) && $res['code']=="OK"){
                        $status[$attr] = 1;
                    }
                    p("good_id:{$status['goods_id']} -- {$attr}:{$status[$attr]}".PHP_EOL.PHP_EOL);
                }
                usleep(800);
            }
            $db->createCommand()->insert('move_ali_log',$status)->execute();
        }
    }

    /**
     * 富文本图片上传顽兔
     * @param int $start
     * @param int $end
     * @throws \yii\db\Exception
     */
    public function actionDescUpload($start=0, $end=0){
        $db = Yii::$app->getDb();
        $data = (new Query())->select("goods_id,goods_desc_images")
            ->from("move_ali_log")
            ->where(['between', 'goods_id', $start, $end])
            ->all($db);
        foreach ($data as $v){

            if(empty($v['goods_desc_images'])){
                continue;
            }
            $imageArr = explode(',', $v['goods_desc_images']);
            $status = 1;
            foreach ($imageArr as $vv){
                //判断图片格式
                $postfix = trim(strrchr($vv, '.'),'.');
                if (in_array($postfix, ["jpg","png","gif","jpeg"])){
//                    p("good_id:{$v['goods_id']} -- ".$postfix.' -- '.$vv.PHP_EOL.PHP_EOL);
                    $res = $this->upload($vv);
                    if (!array_key_exists('code',$res) || $res['code']!="OK"){
                        $status = 0;
                        $res['url'] = "";
                        p($res);
                        //记录上传失败图片
                        $db->createCommand()->insert('move_ali_fail_log',["url"=>$vv, "goods_id"=>$v['goods_id']])->execute();
                    }
                    p("good_id:{$v['goods_id']} -- {$vv} -- {$res['url']}".PHP_EOL.PHP_EOL);
                    usleep(1000);
                }
            }
            $db->createCommand()->update('move_ali_log',["goods_desc"=>$status],["goods_id"=>$v['goods_id']])->execute();
        }
    }

    public function actionGalleryUpload($start=0, $end=0){
        $db = Yii::$app->getDb();
        $data = (new Query())->select("goods_id,img_url,thumb_url,img_original")
            ->from("ecs_goods_gallery")
            ->where(['between', 'goods_id', $start, $end])
            ->all($db);
//        p($data,1);
        foreach ($data as $v){
            $status = 1;
            foreach ($v as $k => $vv){
                if ($k=="goods_id" || empty($vv)){
                    continue;
                }
                //判断图片格式
                $res = $this->upload($vv);
                if (!array_key_exists('code',$res) || $res['code']!="OK"){
                    $status = 0;
                    $res['url'] = "";
                }
                p("good_id:{$v['goods_id']} -- {$vv} -- {$res['url']}".PHP_EOL.PHP_EOL);
                usleep(1000);
            }
            $db->createCommand()->update('move_ali_log',["goods_gallery"=>$status],["goods_id"=>$v['goods_id']])->execute();
        }
    }

    public function actionZw(){
        $wtRes = $this->upload("/images/upload/Image/PBL003桦影贝加尔-1.jpg");
//        $wtRes = $this->uploadAli->test_upload_file_c("E:\phpStudy\PHPTutorial\WWW\hjz\htdocs/images/alishi/PBL003桦影贝加尔-1.jpg", "hjzimage", "/images/upload/Image");
        p($wtRes);
    }

}
