<?php

namespace console\controllers;
use Yii;
use yii\db\Query;

class TestController extends \yii\console\Controller
{
    public function init()
    {
        Yii::$app->setComponents([
            'db'=>[
                'class'       => 'yii\db\Connection',
                'dsn'         => 'mysql:host=gz-cdb-ecmy83dx.sql.tencentcdb.com;port=62387;dbname=bdm314524321_db',
                'username'    => 'root',
                'password'    => 'hjzhome888',
                'charset'     => 'utf8',
                'tablePrefix' => 'ecs_',
            ]
        ]);
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionIndex($start='', $end='')
    {
        Yii::$app->setComponents([
           'db'=>[
               'class'       => 'yii\db\Connection',
               'dsn'         => 'mysql:host=gz-cdb-ecmy83dx.sql.tencentcdb.com;port=62387;dbname=bdm314524321_db',
               'username'    => 'root',
               'password'    => 'hjzhome888',
               'charset'     => 'utf8',
               'tablePrefix' => 'ecs_',
           ]
        ]);
        $info = (new Query())->from("ecs_goods")
            ->select("goods_id,goods_desc,is_real,is_delete,is_on_sale")
            ->where(['between','goods_id',$start,$end])
            ->andWhere("is_real=0 or is_delete=1")
//            ->where(["goods_id"=>212])
            ->all();
//        p($info,1);
//        $regImg = '/<img[^>]*src\s*=\s*[\"|\']?\s*([^>\"\'\s]*)(\">|\"\/>)/i';
//        $imgpreg = '/<img.+src=\"?(.+\.(jpg|gif|bmp|bnp|png))\"?.+>/i';
//        $match_str = "/<img.*srcs*=s*[\"|']?s*([^>\"'s]*)/i";

        foreach ($info as $k=>$v){
//            preg_match_all("/src=\"(.*)\"/U", $v['goods_desc'], $matches);
//            $images = implode(",", $matches[1]);
            p("num:{$k}, goods_id:{$v['goods_id']}, is_real:{$v['is_real']}, is_delete:{$v['is_delete']}".PHP_EOL.PHP_EOL);
            @Yii::$app->db->createCommand()->update('move_ali_log',["goods_desc_images"=>""],["good_id"=>$v['goods_id']])->execute();
            usleep(1000);
        }
//        $this->stdout('hello world');
    }

    public function actionGoodsDesc($start="",$end=""){
        Yii::$app->setComponents([
            'db'=>[
                'class'       => 'yii\db\Connection',
                'dsn'         => 'mysql:host=gz-cdb-ecmy83dx.sql.tencentcdb.com;port=62387;dbname=bdm314524321_db',
                'username'    => 'root',
                'password'    => 'hjzhome888',
                'charset'     => 'utf8',
                'tablePrefix' => 'ecs_',
            ]
        ]);
//        $info = (new Query())->from("ecs_goods")
//            ->select("goods_id,goods_desc,is_real,is_delete,is_on_sale")
//            ->where(['between','goods_id',$start,$end])
//            ->andWhere("is_real=1 and is_delete=0")
//            ->all();
        $info = (new Query())->from("ecs_topic")
            ->select("*")
            ->where(['topic_id'=>4])
            ->all();

        foreach ($info as $k=>$v){
            //添加图片前缀
            $newct = $this->get_img_thumb_url($v['intro'],"http://image.hjzhome.com");
            @Yii::$app->db->createCommand()->update('ecs_topic',["intro"=>$newct],["topic_id"=>4])->execute();
            p("num:{$k}, topic_id:{$v['topic_id']}".PHP_EOL.PHP_EOL);
            usleep(1000);
        }

    }

    /**
     * 主题页详情地址
     */
    public function actionTopicDesc(){
        $data = (new Query())->select("intro")
            ->from("ecs_topic")
            ->where(['in','topic_id',[3]])
            ->column();

        preg_match_all("/src=\"(.*)\"/U", $data[0], $matches);
        $images = implode(",", $matches[1]);
//        p($matches[1]);
        Yii::$app->db->createCommand()->insert('move_ali_log',['goods_id'=>3,"type"=>"topic",'goods_desc_images'=>$images])->execute();
    }

    /**
     * 图片地址替换成压缩URL
     * @param string $content 内容
     * @param string $suffix 后缀
     */
    function get_img_thumb_url($content="",$prefix="",$suffix="")
    {
        // by http://www.manongjc.com/article/1319.html
        $pregRule = "/<[img|IMG].*?src=[\'|\"](.*?(?:[\.jpg|\.jpeg|\.png|\.gif]))[\'|\"].*?[\/]?>/";
        $content = preg_replace($pregRule, '<img src="'.$prefix.'${1}'.$suffix.'" style="max-width:100%">', $content);
        return $content;
    }

    public function actionUpdateImgurl(){
        $str = Yii::$app->db->createCommand()->update("ecs_goods", ["goods_thumb"=>"goods_thumb","tuijie_img"=>"tuijie_img","goods_img"=>"goods_img","original_img"=>"original_img"],[">","goods_id",0])->getRawSql();
        echo $str;
    }

    public function actionUpdateGoodname(){
//        Yii::$app->setComponents([
//            'dbold'=>[
//                'class'       => 'yii\db\Connection',
//                'dsn'         => 'mysql:host=bdm314524321.my3w.com;port=3306;dbname=bdm314524321_db',
//                'username'    => 'bdm314524321',
//                'password'    => 'qdm1241752642016',
//                'charset'     => 'UTF-8',
//                'tablePrefix' => 'ecs_',
//            ]
//        ]);

//        $data = (new Query())->from("ecs_goods")
//            ->select("goods_name,goods_sn")
//            ->where([">","goods_id",3360])
//            ->all(Yii::$app->dbold);
        $data = Yii::$app->dbloc->createCommand("select goods_sn,goods_name from ecs_goods where goods_id>3360")->queryAll();
        foreach ($data as $v){
            Yii::$app->db->createCommand()->update("ecs_goods",["goods_name"=>$v['goods_name']],["goods_sn"=>$v['goods_sn']])->execute();
            $old = iconv("utf-8","gbk",$v['goods_name']);
            p($v['goods_sn']."---".$old);
            usleep(1000);
        }
    }
}
