<?php

namespace console\controllers;
use Yii;
use yii\db\Query;

class TestController extends \yii\console\Controller
{
    public function init()
    {
        Yii::$app->setComponents([
            'db'=>[
                'class'       => 'yii\db\Connection',
                'dsn'         => 'mysql:host=gz-cdb-ecmy83dx.sql.tencentcdb.com;port=62387;dbname=bdm314524321_db',
                'username'    => 'root',
                'password'    => 'hjzhome888',
                'charset'     => 'utf8',
                'tablePrefix' => 'ecs_',
            ]
        ]);
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 本功能已迁移到fake/desc-upload
     * @param string $start
     * @param string $end
     * @throws \yii\db\Exception
     */
    public function actionIndex($start='', $end='')
    {
        $info = (new Query())->from("ecs_goods")
            ->select("goods_id,goods_desc")
//            ->where(['between','goods_id',$start,$end])
            ->andWhere("is_real=0 or is_delete=1")
            ->where(["goods_id"=>1678])
            ->all();
//        p($info,1);
//        $regImg = '/<img[^>]*src\s*=\s*[\"|\']?\s*([^>\"\'\s]*)(\">|\"\/>)/i';
//        $imgpreg = '/<img.+src=\"?(.+\.(jpg|gif|bmp|bnp|png))\"?.+>/i';
//        $match_str = "/<img.*srcs*=s*[\"|']?s*([^>\"'s]*)/i";

        foreach ($info as $k=>$v){
            preg_match_all("/<img src=\"(.*)\"/U", $v['goods_desc'], $matches);
            $images = implode(",", $matches[1]);
            p($matches,1);
            p("num:{$k}, goods_id:{$v['goods_id']}".PHP_EOL.PHP_EOL);
            @Yii::$app->db->createCommand()->update('move_ali_log',["goods_desc_images"=>""],["good_id"=>$v['goods_id']])->execute();
            usleep(800);
        }
    }

    public function actionKj(){
        Yii::$app->setComponents([
            'db_yii'=>[
                'class'       => 'yii\db\Connection',
                'dsn'         => 'mysql:host=gz-cdb-ecmy83dx.sql.tencentcdb.com;port=62387;dbname=yii2admin',
                'username'    => 'root',
                'password'    => 'hjzhome888',
                'charset'     => 'utf8',
            ]
        ]);
        $content = (new Query())->from("yii2_wx_goods")
            ->select("wg_content")
            ->where(["wg_id"=>9])
            ->scalar(Yii::$app->db_yii);
        p($content,0,1);
        $pregRule = "/width(.*)\>/U";
        $content2 = preg_replace($pregRule, '>', $content);
        p($content2,0,1);
        Yii::$app->db_yii->createCommand()->update('yii2_wx_goods',['wg_content'=>$content2],['wg_id'=>9])->execute();
    }

    /**
     * 主题表详情页图片转换
     * @param string $start
     * @param string $end
     * @throws \yii\db\Exception
     */
    public function actionGoodsDesc($start="",$end=""){
//        $info = (new Query())->from("ecs_goods")
//            ->select("goods_id,goods_desc,is_real,is_delete,is_on_sale")
//            ->where(['between','goods_id',$start,$end])
//            ->andWhere("is_real=1 and is_delete=0")
//            ->all();
        $info = (new Query())->from("ecs_topic")
            ->select("*")
            ->where(['topic_id'=>4])
            ->all();

        foreach ($info as $k=>$v){
            //添加图片前缀
            $newct = $this->get_img_thumb_url($v['intro'],"http://image.hjzhome.com");
            @Yii::$app->db->createCommand()->update('ecs_topic',["intro"=>$newct],["topic_id"=>4])->execute();
            p("num:{$k}, topic_id:{$v['topic_id']}".PHP_EOL.PHP_EOL);
            usleep(1000);
        }

    }

    /**
     * 主题页详情地址
     */
    public function actionTopicDesc(){
        $data = (new Query())->select("intro")
            ->from("ecs_topic")
            ->where(['in','topic_id',[3]])
            ->column();

        preg_match_all("/src=\"(.*)\"/U", $data[0], $matches);
        $images = implode(",", $matches[1]);
//        p($matches[1]);
        Yii::$app->db->createCommand()->insert('move_ali_log',['goods_id'=>3,"type"=>"topic",'goods_desc_images'=>$images])->execute();
    }

    /**
     *  图片地址替换成压缩URL
     * @param string $content  内容
     * @param string $prefix
     * @param string $suffix  后缀
     * @return null|string|string[]
     */
    private function get_img_thumb_url($content="",$prefix="",$suffix="")
    {
        $pregRule = "/<[img|IMG].*?src=[\'|\"](.*?(?:[\.jpg|\.jpeg|\.png|\.gif]))[\'|\"].*?[\/]?>/";
        $content = preg_replace($pregRule, '<img src="'.$prefix.'${1}'.$suffix.'" style="max-width:100%">', $content);
        return $content;
    }

}
